Uplaod and read the data

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/medquad.csv")
df

,question,answer,source,focus_area
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea...",NIHSeniorHealth,Glaucoma
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...,NIHSeniorHealth,Glaucoma
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ...",NIHSeniorHealth,Glaucoma
4,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
...,...,...,...,...
16407,What is (are) Diabetic Neuropathies: The Nerve...,Focal neuropathy appears suddenly and affects ...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16408,How to prevent Diabetic Neuropathies: The Nerv...,The best way to prevent neuropathy is to keep ...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16409,How to diagnose Diabetic Neuropathies: The Ner...,Doctors diagnose neuropathy on the basis of sy...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16410,What are the treatments for Diabetic Neuropath...,The first treatment step is to bring blood glu...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16411,What to do for Diabetic Neuropathies: The Nerv...,- Diabetic neuropathies are nerve disorders ca...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...

In [ ]:
df.head()

,question,answer,source,focus_area
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea...",NIHSeniorHealth,Glaucoma
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...,NIHSeniorHealth,Glaucoma
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ...",NIHSeniorHealth,Glaucoma
4,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma

In [ ]:
df.tail()

,question,answer,source,focus_area
16407,What is (are) Diabetic Neuropathies: The Nerve...,Focal neuropathy appears suddenly and affects ...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16408,How to prevent Diabetic Neuropathies: The Nerv...,The best way to prevent neuropathy is to keep ...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16409,How to diagnose Diabetic Neuropathies: The Ner...,Doctors diagnose neuropathy on the basis of sy...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16410,What are the treatments for Diabetic Neuropath...,The first treatment step is to bring blood glu...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...
16411,What to do for Diabetic Neuropathies: The Nerv...,- Diabetic neuropathies are nerve disorders ca...,NIDDK,Diabetic Neuropathies: The Nerve Damage of Dia...

Check the missing Value

In [ ]:
df.isnull().sum()

question       0
answer         5
source         0
focus_area    14
dtype: int64

In [ ]:
df = df.dropna(subset=["question", "answer"])
df = df.drop_duplicates()

Select 30 medical questions

In [ ]:
sample = df.sample(n=30, random_state=42)
sample

,question,answer,source,focus_area
2858,Is Galactosialidosis inherited ?,How is galactosialidosis inherited? Galactosia...,GARD,Galactosialidosis
11213,"Is 17 alpha-hydroxylase/17,20-lyase deficiency...",This condition is inherited in an autosomal re...,GHR,"17 alpha-hydroxylase/17,20-lyase deficiency"
7736,What are the symptoms of Idiopathic inflammato...,What are the signs and symptoms of Idiopathic ...,GARD,Idiopathic inflammatory myopathy
4952,What are the symptoms of 8p23.1 duplication sy...,What are the signs and symptoms of 8p23.1 dupl...,GARD,8p23.1 duplication syndrome
733,What are the treatments for Gum (Periodontal) ...,Controlling the Infection The main goal of tre...,NIHSeniorHealth,Gum (Periodontal) Disease
8258,What are the symptoms of Coronary Microvascula...,The signs and symptoms of coronary microvascul...,NHLBI,Coronary Microvascular Disease
3468,What are the treatments for Gardner-Diamond sy...,How might Gardner-Diamond syndrome be treated?...,GARD,Gardner-Diamond syndrome
8223,Who is at risk for Coronary Heart Disease Risk...,High Blood Cholesterol and Triglyceride Levels...,NHLBI,Coronary Heart Disease Risk Factors
5996,What is (are) Meningioma ?,"Meningiomas originate in the meninges, the mem...",GARD,Meningioma
10870,What is (are) Schwartz-Jampel syndrome ?,Schwartz-Jampel syndrome is a rare condition c...,GHR,Schwartz-Jampel syndrome
11575,What is (are) idiopathic pulmonary fibrosis ?,"Idiopathic pulmonary fibrosis is a chronic, pr...",GHR,idiopathic pulmonary fibrosis
1210,What are the symptoms of Adult Central Nervous...,The signs and symptoms of adult brain and spin...,CancerGov,Adult Central Nervous System Tumors
14169,What are the treatments for fibrodysplasia oss...,These resources address the diagnosis or manag...,GHR,fibrodysplasia ossificans progressiva
3991,What is (are) Menetrier disease ?,Mntrier disease is a condition characterized b...,GARD,Menetrier disease
7617,What are the treatments for Craniometaphyseal ...,How might craniometaphyseal dysplasia be treat...,GARD,"Craniometaphyseal dysplasia, autosomal recessi..."
290,What is (are) Hearing Loss ?,Presbycusis is common in older adults. Presbyc...,NIHSeniorHealth,Hearing Loss
10394,What are the treatments for Lujan syndrome ?,These resources address the diagnosis or manag...,GHR,Lujan syndrome
6728,What is (are) Hemochromatosis ?,Hemochromatosis is a condition in which too mu...,GARD,Hemochromatosis
8557,What are the treatments for Pericarditis ?,Most cases of pericarditis are mild; they clea...,NHLBI,Pericarditis
16139,What are the treatments for Urinary Tract Infe...,"Most UTIs are caused by bacteria, which are tr...",NIDDK,Urinary Tract Infections in Children
12557,What are the genetic changes related to heredi...,HMERF can be caused by a mutation in the TTN g...,GHR,hereditary myopathy with early respiratory fai...
6927,What is (are) Laron syndrome ?,Laron syndrome is a condition that occurs when...,GARD,Laron syndrome
7844,What are the symptoms of Partial agenesis of c...,What are the signs and symptoms of Partial age...,GARD,Partial agenesis of corpus callosum
5301,What are the symptoms of Spondylometaphyseal d...,What are the signs and symptoms of Spondylomet...,GARD,Spondylometaphyseal dysplasia X-linked
11218,Is spastic paraplegia type 15 inherited ?,This condition is inherited in an autosomal re...,GHR,spastic paraplegia type 15
3571,What is (are) Cogan-Reese syndrome ?,Cogan-Reese syndrome is one type of Iridocorne...,GARD,Cogan-Reese syndrome
11639,What are the treatments for cystinosis ?,These resources address the diagnosis or manag...,GHR,cystinosis
2150,What is (are) Atrial Fibrillation ?,An arrhythmia is a problem with the speed or r...,MPlusHealthTopics,Atrial Fibrillation
102,What are the treatments for Anxiety Disorders ?,Exposure-based treatment has been used for man...,NIHSeniorHealth,Anxiety Disorders
3820,What are the symptoms of Non 24 hour sleep wak...,What are the signs and symptoms of Non 24 hour...,GARD,Non 24 hour sleep wake disorder

Display 30 questions

In [ ]:
sample[["question","answer"]]

,question,answer
2858,Is Galactosialidosis inherited ?,How is galactosialidosis inherited? Galactosia...
11213,"Is 17 alpha-hydroxylase/17,20-lyase deficiency...",This condition is inherited in an autosomal re...
7736,What are the symptoms of Idiopathic inflammato...,What are the signs and symptoms of Idiopathic ...
4952,What are the symptoms of 8p23.1 duplication sy...,What are the signs and symptoms of 8p23.1 dupl...
733,What are the treatments for Gum (Periodontal) ...,Controlling the Infection The main goal of tre...
8258,What are the symptoms of Coronary Microvascula...,The signs and symptoms of coronary microvascul...
3468,What are the treatments for Gardner-Diamond sy...,How might Gardner-Diamond syndrome be treated?...
8223,Who is at risk for Coronary Heart Disease Risk...,High Blood Cholesterol and Triglyceride Levels...
5996,What is (are) Meningioma ?,"Meningiomas originate in the meninges, the mem..."
10870,What is (are) Schwartz-Jampel syndrome ?,Schwartz-Jampel syndrome is a rare condition c...
11575,What is (are) idiopathic pulmonary fibrosis ?,"Idiopathic pulmonary fibrosis is a chronic, pr..."
1210,What are the symptoms of Adult Central Nervous...,The signs and symptoms of adult brain and spin...
14169,What are the treatments for fibrodysplasia oss...,These resources address the diagnosis or manag...
3991,What is (are) Menetrier disease ?,Mntrier disease is a condition characterized b...
7617,What are the treatments for Craniometaphyseal ...,How might craniometaphyseal dysplasia be treat...
290,What is (are) Hearing Loss ?,Presbycusis is common in older adults. Presbyc...
10394,What are the treatments for Lujan syndrome ?,These resources address the diagnosis or manag...
6728,What is (are) Hemochromatosis ?,Hemochromatosis is a condition in which too mu...
8557,What are the treatments for Pericarditis ?,Most cases of pericarditis are mild; they clea...
16139,What are the treatments for Urinary Tract Infe...,"Most UTIs are caused by bacteria, which are tr..."
12557,What are the genetic changes related to heredi...,HMERF can be caused by a mutation in the TTN g...
6927,What is (are) Laron syndrome ?,Laron syndrome is a condition that occurs when...
7844,What are the symptoms of Partial agenesis of c...,What are the signs and symptoms of Partial age...
5301,What are the symptoms of Spondylometaphyseal d...,What are the signs and symptoms of Spondylomet...
11218,Is spastic paraplegia type 15 inherited ?,This condition is inherited in an autosomal re...
3571,What is (are) Cogan-Reese syndrome ?,Cogan-Reese syndrome is one type of Iridocorne...
11639,What are the treatments for cystinosis ?,These resources address the diagnosis or manag...
2150,What is (are) Atrial Fibrillation ?,An arrhythmia is a problem with the speed or r...
102,What are the treatments for Anxiety Disorders ?,Exposure-based treatment has been used for man...
3820,What are the symptoms of Non 24 hour sleep wak...,What are the signs and symptoms of Non 24 hour...

Install Required Libraries

In [ ]:
!pip install transformers accelerate

Requirement already satisfied: transformers in /usr/local/lib/python3.13/dist-packages (5.20.2)
Requirement already satisfied: accelerate in /usr/local/lib/python3.13/dist-packages (1.15.0)
Requirement already satisfied: huggingface-hub<3.0,>=1.31.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (1.33.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /usr/local/lib/python3.13/dist-packages (from transformers) (0.23.3)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers) (0.27.3)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.13/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (4.2.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (4.16.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (2026.10.23)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (0.16.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.13/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from accelerate) (2.11.0+cu130)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (13.0.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.85)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch>=2.0.0->accelerate) (1.8.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.4)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

Import Require Library

In [ ]:
import torch
from transformers import pipeline

Load pretrained owned model

In [ ]:
model = pipeline (
    "text-generation",
    model="Qwen/Qwen2.5-1.5B-Instruct",
    device=0 )

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

Test Medical Question Answering

In [ ]:
question = sample.iloc[0]["question"]
question

'Is Galactosialidosis inherited ?'

In [ ]:
result = model(
    [{"role":"user","content": question}],
    max_new_tokens=150,
    do_sample=False
)
result

[{'generated_text': [{'role': 'user',
    'content': 'Is Galactosialidosis inherited ?'},
   {'role': 'assistant',
    'content': "Yes, Galactosialidosis is an autosomal recessive genetic disorder that can be inherited from parents who carry the gene for the condition but do not show symptoms themselves. This means that if both parents are carriers of the gene (having one copy of the mutated gene), there is a 25% chance with each pregnancy that their child will inherit two copies of the mutated gene and develop the disease.\n\nThe inheritance pattern of Galactosialidosis follows Mendelian genetics, specifically X-linked recessive or autosomal recessive patterns depending on the specific type. It's important to note that while it is primarily associated with males due to its involvement in the X chromosome, females may also be affected as they have two X chromosomes, increasing"}]}]

Compare AI Answer with Reference Answer

In [ ]:
print(sample.iloc[0]["answer"])

How is galactosialidosis inherited? Galactosialidosis is inherited in an autosomal recessive pattern, which means both copies of the gene in each cell have mutations. The parents of an individual with an autosomal recessive condition each carry one copy of the mutated gene, but they typically do not show signs and symptoms of the condition.

Evulate 30 medical Questions

In [ ]:
answers=[]
for question in sample["question"]:

    result = model(
    [{"role":"user","content": question}],
    max_new_tokens=150,
    do_sample=False
)
    answers.append(result[0]["generated_text"][-1]["content"])

sample = sample.copy()
sample["ai_answer"] = answers
sample[["question","answer", "ai_answer"]]

,question,answer,ai_answer
2858,Is Galactosialidosis inherited ?,How is galactosialidosis inherited? Galactosia...,"Yes, Galactosialidosis is an autosomal recessi..."
11213,"Is 17 alpha-hydroxylase/17,20-lyase deficiency...",This condition is inherited in an autosomal re...,"Yes, 17α-hydroxylase/17,20-lyase (CYP17) defic..."
7736,What are the symptoms of Idiopathic inflammato...,What are the signs and symptoms of Idiopathic ...,Idiopathic inflammatory myopathy (IIM) is a gr...
4952,What are the symptoms of 8p23.1 duplication sy...,What are the signs and symptoms of 8p23.1 dupl...,8p23.1 duplication syndrome is also known as W...
733,What are the treatments for Gum (Periodontal) ...,Controlling the Infection The main goal of tre...,"Gum disease, also known as periodontal disease..."
8258,What are the symptoms of Coronary Microvascula...,The signs and symptoms of coronary microvascul...,Coronary microvascular disease (CMD) is a cond...
3468,What are the treatments for Gardner-Diamond sy...,How might Gardner-Diamond syndrome be treated?...,Gardner-Diamond syndrome is a rare genetic dis...
8223,Who is at risk for Coronary Heart Disease Risk...,High Blood Cholesterol and Triglyceride Levels...,Coronary heart disease (CHD) risk factors can ...
5996,What is (are) Meningioma ?,"Meningiomas originate in the meninges, the mem...",Meningiomas are benign tumors that develop fro...
10870,What is (are) Schwartz-Jampel syndrome ?,Schwartz-Jampel syndrome is a rare condition c...,Schwartz-Jampel Syndrome is a rare genetic dis...
11575,What is (are) idiopathic pulmonary fibrosis ?,"Idiopathic pulmonary fibrosis is a chronic, pr...",Idiopathic pulmonary fibrosis (IPF) is a chron...
1210,What are the symptoms of Adult Central Nervous...,The signs and symptoms of adult brain and spin...,Adult central nervous system (CNS) tumors can ...
14169,What are the treatments for fibrodysplasia oss...,These resources address the diagnosis or manag...,Fibrodysplasia ossificans progressiva (FOP) is...
3991,What is (are) Menetrier disease ?,Mntrier disease is a condition characterized b...,Menetrier's disease is a rare disorder charact...
7617,What are the treatments for Craniometaphyseal ...,How might craniometaphyseal dysplasia be treat...,Craniometaphyseal dysplasia is an extremely ra...
290,What is (are) Hearing Loss ?,Presbycusis is common in older adults. Presbyc...,Hearing loss can be defined as the partial or ...
10394,What are the treatments for Lujan syndrome ?,These resources address the diagnosis or manag...,Lujan syndrome is a rare genetic disorder that...
6728,What is (are) Hemochromatosis ?,Hemochromatosis is a condition in which too mu...,Hemochromatosis is a genetic disorder that cau...
8557,What are the treatments for Pericarditis ?,Most cases of pericarditis are mild; they clea...,Pericarditis is an inflammation of the pericar...
16139,What are the treatments for Urinary Tract Infe...,"Most UTIs are caused by bacteria, which are tr...",Urinary tract infections (UTIs) in children ca...
12557,What are the genetic changes related to heredi...,HMERF can be caused by a mutation in the TTN g...,Hereditary myopathies are a group of inherited...
6927,What is (are) Laron syndrome ?,Laron syndrome is a condition that occurs when...,Laron syndrome is a rare genetic disorder that...
7844,What are the symptoms of Partial agenesis of c...,What are the signs and symptoms of Partial age...,Partial agenesis of the corpus callosum (PACC)...
5301,What are the symptoms of Spondylometaphyseal d...,What are the signs and symptoms of Spondylomet...,Spondylometaphyseal dysplasia (SM) is an inher...
11218,Is spastic paraplegia type 15 inherited ?,This condition is inherited in an autosomal re...,"Yes, Spastic Paraplegia Type 15 (SPG15) is an ..."
3571,What is (are) Cogan-Reese syndrome ?,Cogan-Reese syndrome is one type of Iridocorne...,Cogan-Reese syndrome refers to a group of rare...
11639,What are the treatments for cystinosis ?,These resources address the diagnosis or manag...,Cystinosis is an inherited disorder that affec...
2150,What is (are) Atrial Fibrillation ?,An arrhythmia is a problem with the speed or r...,Atrial fibrillation (AFib or AF) is an irregul...
102,What are the treatments for Anxiety Disorders ?,Exposure-based treatment has been used for man...,Anxiety disorders can be treated with various ...
3820,What are the symptoms of Non 24 hour sleep wak...,What are the signs and symptoms of Non 24 hour...,Non-24-hour sleep-wake disorder is a circadian...

Identify Medical Answering Failures

In [ ]:
print(sample.iloc[0]["question"])
print(sample.iloc[0]["answer"])
print(sample.iloc[0]["ai_answer"])

Is Galactosialidosis inherited ?
How is galactosialidosis inherited? Galactosialidosis is inherited in an autosomal recessive pattern, which means both copies of the gene in each cell have mutations. The parents of an individual with an autosomal recessive condition each carry one copy of the mutated gene, but they typically do not show signs and symptoms of the condition.
Yes, Galactosialidosis is an autosomal recessive genetic disorder that can be inherited from parents who carry the gene for the condition but do not show symptoms themselves. This means that if both parents are carriers of the gene (having one copy of the mutated gene), there is a 25% chance with each pregnancy that their child will inherit two copies of the mutated gene and develop the disease.

The inheritance pattern of Galactosialidosis follows Mendelian genetics, specifically X-linked recessive or autosomal recessive patterns depending on the specific type. It's important to note that while it is primarily associated with males due to its involvement in the X chromosome, females may also be affected as they have two X chromosomes, increasing

In [ ]:
print(sample.iloc[1]["question"])
print(sample.iloc[1]["answer"])
print(sample.iloc[1]["ai_answer"])

Is 17 alpha-hydroxylase/17,20-lyase deficiency inherited ?
This condition is inherited in an autosomal recessive pattern, which means both copies of the gene in each cell have mutations. The parents of an individual with an autosomal recessive condition each carry one copy of the mutated gene, but they typically do not show signs and symptoms of the condition.
Yes, 17α-hydroxylase/17,20-lyase (CYP17) deficiency is an autosomal recessive genetic disorder that can be inherited. This condition affects the production of androgens in the body, leading to various symptoms such as delayed puberty, infertility, and hormonal imbalances.

The inheritance pattern for CYP17 deficiency is typically X-linked recessive, but it can also occur in females with mutations on the Y chromosome or in males with mutations on both the X and Y chromosomes. The severity of the condition can vary depending on the specific mutation involved and whether there are additional genetic factors contributing to the disease.

If you have any more questions about this topic or need further information,

Test why this happens

In [ ]:
question = "Is 17 alpha-hydroxylase/17,20-lyase deficiency inherited? Answer in one sentence."

result = model(
    [{"role": "user", "content": question}],
    max_new_tokens=150,
    do_sample=False
)

print(result[0]["generated_text"][-1]["content"])

Yes, 17alpha-hydroxylase/17,20-lyase deficiency is an autosomal recessive genetic disorder.

In [ ]:
question = "Is Galactosialidosis inherited ? Answer in one sentence."
result = model(
    [{"role": "user", "content": question}],
    max_new_tokens=150,
    do_sample=False
)

print(result[0]["generated_text"][-1]["content"])

Yes, Galactosialidosis is an autosomal recessive genetic disorder.

Investigate Failure 2: Medical Treatment Recommendations

In [ ]:

sample[sample["question"].str.contains("treatments", case=False)][["question", "answer", "ai_answer"]]

,question,answer,ai_answer
733,What are the treatments for Gum (Periodontal) ...,Controlling the Infection The main goal of tre...,"Gum disease, also known as periodontal disease..."
3468,What are the treatments for Gardner-Diamond sy...,How might Gardner-Diamond syndrome be treated?...,Gardner-Diamond syndrome is a rare genetic dis...
14169,What are the treatments for fibrodysplasia oss...,These resources address the diagnosis or manag...,Fibrodysplasia ossificans progressiva (FOP) is...
7617,What are the treatments for Craniometaphyseal ...,How might craniometaphyseal dysplasia be treat...,Craniometaphyseal dysplasia is an extremely ra...
10394,What are the treatments for Lujan syndrome ?,These resources address the diagnosis or manag...,Lujan syndrome is a rare genetic disorder that...
8557,What are the treatments for Pericarditis ?,Most cases of pericarditis are mild; they clea...,Pericarditis is an inflammation of the pericar...
16139,What are the treatments for Urinary Tract Infe...,"Most UTIs are caused by bacteria, which are tr...",Urinary tract infections (UTIs) in children ca...
11639,What are the treatments for cystinosis ?,These resources address the diagnosis or manag...,Cystinosis is an inherited disorder that affec...
102,What are the treatments for Anxiety Disorders ?,Exposure-based treatment has been used for man...,Anxiety disorders can be treated with various ...

Compare one treatment question

In [ ]:
print(sample.loc[8557, "answer"])
print(sample.loc[8557, "ai_answer"])

Most cases of pericarditis are mild; they clear up on their own or with rest and simple treatment. Other times, more intense treatment is needed to prevent complications. Treatment may include medicines and, less often, procedures or surgery.

The goals of treatment include:

Reducing pain and inflammation

Treating the underlying cause, if it's known

Checking for complications

Specific Types of Treatment

As a first step in your treatment, your doctor may advise you to rest until you feel better and have no fever. He or she may tell you to take over-the-counter, anti-inflammatory medicines to reduce pain and inflammation. Examples of these medicines include aspirin and ibuprofen.

You may need stronger medicine if your pain is severe. If your pain continues to be severe, your doctor may prescribe a medicine called colchicine and, possibly, prednisone (a steroid medicine).

If an infection is causing your pericarditis, your doctor will prescribe an antibiotic or other medicine to treat the infection.

You may need to stay in the hospital during treatment for pericarditis so your doctor can check you for complications.

The symptoms of acute pericarditis can last from a few days to 3 weeks. Chronic pericarditis may last several months.

Other Types of Treatment

You may need treatment for complications of pericarditis. Two serious complications are cardiac tamponade and chronic constrictive pericarditis.

Cardiac tamponade is treated with a procedure called pericardiocentesis (per-ih-KAR-de-o-sen-TE-sis). A needle or tube (called a catheter) is inserted into the chest wall to remove excess fluid in the pericardium. This procedure relieves pressure on the heart.

The only cure for chronic constrictive pericarditis is surgery to remove the pericardium. This is known as a pericardiectomy (PER-i-kar-de-EK-to-me).

The treatments for these complications require hospital stays.
Pericarditis is an inflammation of the pericardium, which is the thin sac that surrounds the heart. The treatment for pericarditis depends on its cause and severity. Here are some common treatments:

1. Medications: Antibiotics may be used to treat bacterial pericarditis. Nonsteroidal anti-inflammatory drugs (NSAIDs) can help reduce pain and swelling.

2. Pain management: Pain relief medications such as opioids or non-opioid analgesics may be prescribed to manage symptoms.

3. Fluid restriction: In cases where fluid builds up in the pericardium, diuretics may be given to help remove excess fluid.

4. Blood transfusions: If there's significant blood loss due to

Test why Failure 2 happens

In [ ]:
question = "A patient has cardiac tamponade caused by fluid around the heart. What is the appropriate treatment?"

result = model(
    [{"role": "user", "content": question}],
    max_new_tokens=150,
    do_sample=False
)

print(result[0]["generated_text"][-1]["content"])

Cardiac tamponade is a serious medical condition where there's an accumulation of fluid or blood around the heart, which can compress the heart and reduce its ability to pump effectively. This situation requires immediate attention and specialized care.

The appropriate treatment for cardiac tamponade typically involves:

1. **Emergency Medical Care**: The first priority is to stabilize the patient's vital signs, including blood pressure, heart rate, and oxygen saturation levels.

2. **Fluid Removal**: In most cases, the goal is to remove the excess fluid from around the heart as quickly as possible. This may involve:
   - **Paracentesis**: A procedure where a needle is inserted into the abdomen to drain accumulated fluid.
   - **Thoracentesis**: Similar to par

Test Procedure Knowledge

In [ ]:
question = "What procedure removes fluid from the pericardial sac?"

result = model(
    [{"role": "user", "content": question}],
    max_new_tokens=100,
    do_sample=False
)

print(result[0]["generated_text"][-1]["content"])

The procedure you're referring to is called pericardiocentesis. It's a medical procedure used to remove excess fluid from the pericardium, which is the thin layer of tissue that surrounds the heart and lungs. This can be done for various reasons, such as managing symptoms caused by excessive fluid buildup or diagnosing conditions like pericarditis (inflammation of the pericardium). The process typically involves inserting a needle into the pericardial space under ultrasound guidance

Measure Failure 2: Medical Procedure Accuracy

In [ ]:
questions = [
    "What procedure removes fluid from the pericardial sac?",
    "What procedure removes fluid from the pleural space?",
    "What procedure removes fluid from the abdomen?",
    "A patient has cardiac tamponade. What procedure is needed?",
    "A patient has pleural effusion. What procedure removes the fluid?"
]

for question in questions:
    result = model(
        [{"role": "user", "content": question}],
        max_new_tokens=100,
        do_sample=False
    )
    print(question)
    print(result[0]["generated_text"][-1]["content"])

What procedure removes fluid from the pericardial sac?
The procedure you're referring to is called pericardiocentesis. It's a medical procedure used to remove excess fluid from the pericardium, which is the thin layer of tissue that surrounds the heart and lungs. This can be done for various reasons, such as managing symptoms caused by excessive fluid buildup or diagnosing conditions like pericarditis (inflammation of the pericardium). The process typically involves inserting a needle into the pericardial space under ultrasound guidance
What procedure removes fluid from the pleural space?
The procedure that removes fluid from the pleural space is called thoracentesis. This procedure involves inserting a needle into the chest cavity to remove excess fluid that has accumulated in the pleural space. The fluid is then collected and sent for analysis to determine its cause. Thoracentesis can be performed as an outpatient procedure or as part of a hospital stay, depending on the patient's condition and the amount of fluid removed.
What procedure removes fluid from the abdomen?
The procedure that removes fluid from the abdomen is called paracentesis. This is typically done under local anesthesia and involves inserting a needle into the abdominal cavity to remove excess fluid. The fluid is then collected in a syringe or bottle for analysis. Paracentesis can be used to diagnose conditions such as liver disease, kidney failure, or heart failure, among others. It may also be performed to relieve pressure on organs in the abdomen caused by fluid buildup.
A patient has cardiac tamponade. What procedure is needed?
Cardiac tamponade occurs when there is an accumulation of fluid or blood in the pericardial sac surrounding the heart. This can lead to reduced blood flow to the heart and other organs due to compression from the accumulated fluid.

The primary treatment for cardiac tamponade involves addressing the underlying cause that led to the accumulation of fluid or blood. However, if the condition is severe enough to require urgent intervention, the following procedures may be necessary:

1. **Pericardiocentesis**:
A patient has pleural effusion. What procedure removes the fluid?
The procedure that removes pleural effusion is called thoracentesis.

Test 5 variations

In [ ]:
questions = [
    "How should cardiac tamponade be treated?",
    "A patient has fluid compressing the heart. What treatment is needed?",
    "What is the emergency treatment for cardiac tamponade?",
    "A patient has fluid in the pericardial sac causing low blood pressure. What should doctors do?",
    "How do doctors remove fluid around the heart during cardiac tamponade?"
]

for question in questions:
    result = model(
        [{"role": "user", "content": question}],
        max_new_tokens=150,
        do_sample=False
    )
    print(question)
    print(result[0]["generated_text"][-1]["content"])

How should cardiac tamponade be treated?
Cardiac tamponade is a medical emergency that requires immediate treatment to prevent serious complications such as shock and organ failure. The primary goal of management is to relieve the pressure on the heart and restore normal blood flow.

Here are some key steps in treating cardiac tamponade:

1. **Emergency Medical Care**: If you suspect cardiac tamponade, seek urgent medical attention immediately. Cardiac tamponade can rapidly lead to life-threatening conditions if not addressed promptly.

2. **Diagnostic Imaging**: Chest X-rays or CT scans may be used to confirm the presence of fluid in the pericardium (the sac surrounding the heart).

3. **Fluid Drainage**: In most cases, the first step is to remove the excess fluid from the per
A patient has fluid compressing the heart. What treatment is needed?
If a patient's heart is being compressed by fluid, it indicates that there may be an accumulation of fluid in the pericardium (the sac surrounding the heart). This condition is known as cardiac tamponade or pericardial effusion.

The primary treatment for this situation involves addressing the underlying cause and managing symptoms to prevent further complications:

1. **Diagnosis**: First, medical professionals will need to determine the cause of the fluid buildup. This can involve imaging studies such as echocardiography, CT scans, or MRI to assess the extent of the fluid and its impact on the heart function.

2. **Fluid Drainage**: If the fluid is causing significant pressure on the heart, draining it might be necessary. This could be
What is the emergency treatment for cardiac tamponade?
Cardiac tamponade is a medical condition where there's an accumulation of fluid in the pericardial sac surrounding the heart, which can compress the heart and reduce its ability to pump blood effectively. This can be life-threatening if not treated promptly.

The primary goal of emergency treatment for cardiac tamponade is to relieve the pressure on the heart and restore normal blood flow. Here are some key steps that may be taken:

1. **Immediate Medical Attention**: The patient should be brought to the nearest hospital or urgent care center as soon as possible.

2. **Fluid Removal**: In most cases, the first step is to remove the excess fluid from the pericardial space. This might involve:
   - **Paracentesis**: A
A patient has fluid in the pericardial sac causing low blood pressure. What should doctors do?
In this situation, doctors would need to carefully consider several factors before deciding on the best course of action:

1. **Fluid Volume and Pressure**: The amount of fluid in the pericardium (the sac surrounding the heart) is crucial. If there's only minimal fluid accumulation, it might be managed conservatively with medications or monitoring.

2. **Patient Condition**: The overall health status of the patient is important. For example, if the patient is very ill or frail, aggressive treatment may not be advisable due to potential complications.

3. **Medical History**: Previous treatments for similar conditions can provide insights into what might work well or poorly.

4. **Consultation with Specialists**: Cardiologists, interventional cardiologists, and possibly other specialists
How do doctors remove fluid around the heart during cardiac tamponade?
Cardiac tamponade is a serious condition where there's an accumulation of blood or other fluids in the space between the heart and its protective sac (pericardium). This can compress the heart, reducing its ability to pump effectively. To treat this condition, doctors typically perform a procedure called pericardiocentesis.

Here’s how it works:

1. **Preparation**: The patient is given general anesthesia to ensure they are asleep and pain-free during the procedure.
2. **Access**: A small incision is made in the chest wall near the location of the fluid buildup.
3. **Drainage**: Using a needle or a catheter, the doctor removes the excess fluid from the pericardial cavity. This may

Tested Qwen2.5-1.5B-Instruct using five variations of cardiac tamponade questions. The model correctly identified pericardiocentesis in one response, provided partially correct answers in two, and produced incorrect or potentially unsafe recommendations in two. Results suggest that medical response accuracy can vary depending on question phrasing.